/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package generagrafico;
import dk.brics.automaton.RegExp;
import dk.brics.automaton.Automaton;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.io.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Alex
 */
public class forma1 extends javax.swing.JFrame{
    public Pattern p;
    public String exp = "";
    public int contador = 0;
    public String mensaje = "", grafo="";
    public String er1 = "", er2="", ejemplo="";
    private FileWriter archivo = null;
    private PrintWriter pw = null;
    private String rutaDot = "C:\\Program Files (x86)\\Graphviz\\bin\\dot.exe";
    String textoBase = "C:\\Automatas\\grafo1.txt"; //La expresión regular
    String imagen = "C:\\Automatas\\grafo1.jpg"; //la imágen del autómata
    String parametroT = "-Tjpg"; //parámetro para el tipo de imagen que se va a devolver
    String parametroO = "-o"; //Parámetro para el programa objeto
    
    /**
     * Creates new form forma1
     */
    public forma1() {
        initComponents();
        this.getContentPane().setBackground(new Color(0,102,255));
        lbIndicaAutomata.setVisible(false);
        this.setSize(900, 550);
        jLabel2.setVisible(false);
        tfcadena.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfExpresionRegular = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbIndicaAutomata = new javax.swing.JLabel();
        btCargarER = new javax.swing.JButton();
        btVerAutomata = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfcadena = new javax.swing.JTextField();
        lbEjemploCadena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setForeground(new java.awt.Color(0, 102, 255));
        setMaximumSize(new java.awt.Dimension(500, 250));
        setMinimumSize(new java.awt.Dimension(500, 250));
        setPreferredSize(new java.awt.Dimension(500, 250));
        getContentPane().setLayout(null);
        getContentPane().add(tfExpresionRegular);
        tfExpresionRegular.setBounds(340, 50, 180, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Ingrese la expresión regular");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 230, 30);

        lbIndicaAutomata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbIndicaAutomata);
        lbIndicaAutomata.setBounds(240, 90, 360, 40);

        btCargarER.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btCargarER.setText("Cargar Expresion Regular");
        btCargarER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarERActionPerformed(evt);
            }
        });
        getContentPane().add(btCargarER);
        btCargarER.setBounds(70, 90, 210, 30);

        btVerAutomata.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btVerAutomata.setText("Ver Imagen del Automata");
        btVerAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerAutomataActionPerformed(evt);
            }
        });
        getContentPane().add(btVerAutomata);
        btVerAutomata.setBounds(600, 90, 210, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("ingrese la cadena a evaluar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 160, 310, 23);
        getContentPane().add(tfcadena);
        tfcadena.setBounds(500, 160, 180, 30);
        getContentPane().add(lbEjemploCadena);
        lbEjemploCadena.setBounds(240, 200, 370, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCargarERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarERActionPerformed
        if(contador == 0)
        { 
            exp = ajustar_expresion(tfExpresionRegular.getText());
            reinicio();
            borraArchivo(textoBase);
            borraArchivo(imagen);
            convierteCadena();
            revisaCadena();
            ejemploCadena();
            grafico();
            creaTexto();
            creaImagen();
            crear_expresion(exp);
            contador = 1;
            jLabel1.setVisible(false);
            jLabel2.setVisible(true);
            tfExpresionRegular.setVisible(false);
            tfcadena.setVisible(true);
            btCargarER.setText("Ingresar cadena");
            contador++;
        }
        else
        {
            Matcher m = p.matcher(tfcadena.getText());
            if(m.matches() == true)
            {
                JOptionPane.showMessageDialog(null, "la cadena " + tfcadena.getText() + " es una cadena aceptada");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "la cadena " + tfcadena.getText() + " no es una cadena aceptada");
            }
        }
    }//GEN-LAST:event_btCargarERActionPerformed
    private String ajustar_expresion(String expresion)
    {
        String nueva_expresion = "";
        for(int i = 0; i < expresion.length(); i++)
        {
            char elemento = expresion.charAt(i);
            if(((int) elemento == 42) && (i < expresion.length() - 1))
            {
                if((int) expresion.charAt(i + 1) == 42)
                {
                    nueva_expresion = nueva_expresion + elemento;
                    for(int j = i + 1; j < expresion.length(); j++)
                    {
                        if((int) expresion.charAt(j) != 42)
                        {
                            i = j - 1;
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Se encontró un error, corregido");
                }
                else nueva_expresion = nueva_expresion + elemento;
            }
            else if(((int) elemento == 43) && (i < expresion.length() - 1))
            {
                if((int) expresion.charAt(i + 1) == 43)
                {
                    nueva_expresion = nueva_expresion + elemento;
                    for(int j = i + 1; j < expresion.length(); j++)
                    {
                        if((int) expresion.charAt(j) != 43)
                        {
                            i = j - 1;
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Se encontró un error, corregido");
                } else nueva_expresion = nueva_expresion + elemento;
            }
            else if(((int) elemento == 124 && (i < expresion.length() - 1)))
            {
                if((int) expresion.charAt(i + 1) == 124)
                {
                    nueva_expresion = nueva_expresion + elemento;
                    for(int j = i + 1; j < expresion.length(); j++)
                    {
                        if((int) expresion.charAt(j) != 124)
                        {
                            i = j - 1;
                            break;
                        }
                    }
                    JOptionPane.showMessageDialog(null, "Se encontró un error, corregido");
                } else nueva_expresion = nueva_expresion + elemento;
            } else nueva_expresion = nueva_expresion + elemento;
        }
        return nueva_expresion;
    }
    private void btVerAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerAutomataActionPerformed
        repaint();
        new imagenAutomata().setVisible(true);
    }//GEN-LAST:event_btVerAutomataActionPerformed
    private void crear_expresion(String cadena)
    {
        p = Pattern.compile(cadena);
    }
    private void convierteCadena(){
        //er1 = tfExpresionRegular.getText();
        er1 = exp;
        for (int j=0; j< er1.length();j++){
            char letra = er1.charAt(j);
            int ascii = (int) letra;
            //System.out.print(ascii);
            if (ascii == 32){
                er2=er2+" ";
            }
            else{
                er2=er2+letra;
            }
        }
    }
    
    private void revisaCadena(){
        //er2 = tfExpresionRegular.getText();
        er2 = exp;
        for (int i=0; i< er2.length();i++){
            char token = er2.charAt(i);
            //int ascii = (int) token;
            //System.out.print(ascii);
            //if (ascii == 32){
            if (token == ' '){
                mensaje = "La expresion regular representa un AFND";
                break;
            }
            else{
                mensaje = "La expresion regular representa un AFD";
            }
        }
        lbIndicaAutomata.setText(mensaje);
        lbIndicaAutomata.setVisible(true);
    }
    
    private void grafico(){
        //System.out.print(er2);
        RegExp exp_reg = new RegExp(er2);
        Automaton aut = exp_reg.toAutomaton();
        grafo = aut.toDot();
        //System.out.println(grafo);
    }
    
    public void creaTexto(){
        try{
                archivo = new FileWriter(textoBase);
                pw = new PrintWriter(archivo);
                grafo = grafo.replace("u0020","Ɛ");
                pw.write(grafo);
                archivo.close();
                grafo="";
        }
        catch(IOException e){
            System.err.println("ERROR en archivo: "+ e.toString());
        }
    }
    
    public void creaImagen(){
        try{
            String[] cmd = new String[5];
            cmd[0] = rutaDot;
            cmd[1] = parametroT;
            cmd[2] = textoBase;
            cmd[3] = parametroO;
            cmd[4] = imagen;

            Runtime rt = Runtime.getRuntime();

            rt.exec(cmd);
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void borraArchivo(String path){
        File archivo = new File(path);
        archivo.delete();
    }
    
    public void reinicio(){
        /**
         * se inician de nuevo las variables
         * para su uso en una nueva expresión regular
         */
        lbIndicaAutomata.setText("");
        lbIndicaAutomata.setVisible(false);
        mensaje = ""; 
        grafo= "";
        er1 = ""; 
        er2= "";
        ejemplo = "";
        archivo = null;
        pw=null;
    }
    
    public void ejemploCadena(){
        int cont=0;
        for (int i=0; i< er2.length();i++){
            char token = er2.charAt(i);
            if (token == '*' || token == '+'){
                cont=cont+1;
            }
        }
        if (cont==0){
            ejemplo=er2;
            ejemplo = ejemplo.replace(" ","");
        }
        else
            ejemplo = ejemploEspecial(er2);
        lbEjemploCadena.setText("Cadena valida de la ER: "+ejemplo);
        lbEjemploCadena.setVisible(true);
    }
    
    public String ejemploEspecial(String cadena){
        String kleene="";
        cadena=cadena.replace("+","");
        for (int i=0; i< cadena.length();i++){
            char token = cadena.charAt(i);
            if (token == '*'){
                kleene=cadena.charAt(i-1)+"*";
                cadena=cadena.replace(kleene,"  ");                
            }
        }
        cadena = cadena.replace(" ","");
        return cadena;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forma1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forma1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forma1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forma1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forma1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCargarER;
    private javax.swing.JButton btVerAutomata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbEjemploCadena;
    private javax.swing.JLabel lbIndicaAutomata;
    private javax.swing.JTextField tfExpresionRegular;
    private javax.swing.JTextField tfcadena;
    // End of variables declaration//GEN-END:variables
}
